-- 0000_crm_schema.sql
-- RELI CRM base schema — reconstructed from the live 4K-Cleaning structure.
-- STRUCTURE ONLY: no client data was copied.
-- Run this in the RELI project BEFORE 0001_timeclock.sql.
--
-- Notes:
--  * CRM tables use text ids (generated by the app), reproduced as-is.
--  * The duplicate snake_case + camelCase columns (created_at/created,
--    contact_id/contactId, balance_due/balanceDue, ...) are legacy from the
--    4K app and are reproduced verbatim so the ported CRM code keeps working.
--  * RLS is baked in: CRM tables are admin/owner-only, so a cleaner who can
--    sign in to the time clock cannot read client data. The public website
--    contact form can still insert leads.

-- ── contacts ───────────────────────────────────────────────
create table if not exists public.contacts (
  id               text primary key,
  business         text not null,
  contact          text,
  phone            text,
  email            text,
  address          text,
  status           text default 'lead',
  notes            text,
  services         jsonb default '[]'::jsonb,
  invoices         jsonb default '[]'::jsonb,
  balance          text default '0',
  balance_due      text,
  created_at       timestamptz default now(),
  updated          timestamptz default now(),
  created          timestamp,
  "balanceDue"     text default '',
  stage            text,
  tasks            jsonb default '[]'::jsonb,
  "contractSigned" boolean
);

-- ── events ─────────────────────────────────────────────────
create table if not exists public.events (
  id           text primary key,
  type         text default 'clean',
  title        text,
  contact_id   text references public.contacts(id) on delete set null,
  date         text,
  start_time   text,
  duration     text,
  cleaners     jsonb default '[]'::jsonb,
  address      text,
  notes        text,
  recur        text default 'none',
  recur_n      text,
  recur_end    text default 'never',
  recur_count  text,
  recur_until  text,
  created_at   timestamptz default now(),
  updated      timestamptz default now(),
  "contactId"  text,
  "start"      text,
  "recurN"     text,
  "recurEnd"   text,
  "recurCount" text,
  "recurUntil" text,
  created      timestamp
);

-- ── event_overrides ────────────────────────────────────────
create table if not exists public.event_overrides (
  id        text primary key,
  event_id  text references public.events(id) on delete cascade,
  date      text,
  data      jsonb,
  created   timestamptz default now()
);

-- ── deleted_events ─────────────────────────────────────────
create table if not exists public.deleted_events (
  id       text primary key,
  created  timestamptz default now()
);

-- ── leads ──────────────────────────────────────────────────
create table if not exists public.leads (
  id          text primary key,
  business    text,
  contact     text,
  phone       text,
  email       text,
  service     text,
  source      text,
  notes       text,
  contact_id  text references public.contacts(id) on delete set null,
  converted   boolean default false,
  created_at  timestamptz default now(),
  updated     timestamptz default now(),
  created     timestamp,
  "contactId" text,
  status      text default 'new',
  tasks       jsonb
);

-- ── prospects ──────────────────────────────────────────────
create table if not exists public.prospects (
  id          text primary key,
  name        text,
  phone       text,
  service     text,
  address     text,
  notes       text,
  status      text default 'new',
  source      text default 'manual',
  created_at  timestamptz default now(),
  updated     timestamptz default now(),
  created     timestamp
);

-- ── staff ──────────────────────────────────────────────────
create table if not exists public.staff (
  id           text primary key,
  name         text not null,
  phone        text,
  email        text,
  address      text,
  emergency    text,
  status       text default 'active',
  paytype      text default 'perjob',
  rate         text,
  paysched     text default 'biweekly',
  notes        text,
  availability jsonb default '[]'::jsonb,
  created_at   timestamptz default now(),
  updated      timestamptz default now(),
  role         text,
  created      timestamp
);

-- ── profiles (one row per Supabase Auth user) ──────────────
create table if not exists public.profiles (
  id                  uuid primary key references auth.users(id) on delete cascade,
  email               text,
  name                text,
  role                text not null default 'staff',
  created_at          timestamptz not null default now(),
  last_seen_changelog bigint
);

-- Auto-create a profile row whenever a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'staff')
  on conflict (id) do nothing;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── Admin check (also (re)defined in 0001_timeclock.sql — identical) ──
create or replace function public.is_ops_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(
    (select p.role in ('admin','owner') from public.profiles p where p.id = auth.uid()),
    false);
$$;

-- ── Row Level Security ─────────────────────────────────────
alter table public.contacts        enable row level security;
alter table public.events          enable row level security;
alter table public.event_overrides enable row level security;
alter table public.deleted_events  enable row level security;
alter table public.prospects       enable row level security;
alter table public.staff           enable row level security;
alter table public.leads           enable row level security;
alter table public.profiles        enable row level security;

-- CRM tables: admin/owner only (protects client data from cleaner logins).
do $$
declare t text;
begin
  foreach t in array array['contacts','events','event_overrides','deleted_events','prospects','staff']
  loop
    execute format('drop policy if exists %1$s_admin on public.%1$s', t);
    execute format('create policy %1$s_admin on public.%1$s for all to authenticated using (public.is_ops_admin()) with check (public.is_ops_admin())', t);
  end loop;
end $$;

-- leads: the public website contact form inserts with the anon key; only
-- admins can read or manage them.
drop policy if exists leads_public_insert on public.leads;
create policy leads_public_insert on public.leads
  for insert to anon, authenticated with check (true);
drop policy if exists leads_admin_all on public.leads;
create policy leads_admin_all on public.leads
  for all to authenticated using (public.is_ops_admin()) with check (public.is_ops_admin());

-- profiles: you see/update your own; admins see all.
drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles
  for select to authenticated using (id = auth.uid() or public.is_ops_admin());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists profiles_admin on public.profiles;
create policy profiles_admin on public.profiles
  for all to authenticated using (public.is_ops_admin()) with check (public.is_ops_admin());
